// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import FormsController from "./forms_controller"
application.register("forms", FormsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import OrderItemsController from "./order_items_controller"
application.register("order-items", OrderItemsController)

import TestController from "./test_controller"
application.register("test", TestController)
